### ISSUE TITLE
Where is any description?

### ISSUE THREAD

**Issue by beeyev** [paleg/goredirector#1]
Could you please describe how to install and use it?

**Comment by paleg** [comment]
To be honest - I was internal project as I needed redirector with:
* Active Directory integration
* https certificates check
* ability to reload with SIGHUP (without restarting squid)
* and (as I used rejik at that moment) compatible with [rejik](http://rejik.ru/) by URL databases and configuration file.

I was not sure that it can be interesting for someone else :)

You can use it as a drop-in replacement for rejik. So, install and configure rejik, and then just replace rejik binary with goredirector binary, it should work.
Active Directory specific configuration directives are described in redirector.conf.dist.
